import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "IlHwakCheonGuem",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex items-center bg-(--color-theme-orange) text-white h-16 px-4">
          {/* Logo */}
          <a href="./main" className="mr-8 font-bold text-xl">
            <img src="/logoText.png" alt="Logo" className="h-8 w-24 inline-block mr-2" />
          </a>

          {/* Navigation Items */}
          <div className="flex space-x-8">
            <a href="./exchange" className="hover:text-blue-300">거래소</a>
            <div className="relative group">
              <a href="#" className="flex items-center hover:text-blue-300">
                서비스+
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 ml-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                </svg>
              </a>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
